server:
  port: 80

management:
  endpoints.web.base-path: /
  endpoint.health.show-details: always

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@

spring:
  data:
    mongodb:
      database: mymoneydb
      host: localhost
      port: 27017